nav:
  - index.md
  - Typography: typography.md
  - Smart Symbols: smart-symbols.md
  - Keyboard Keys: keyboard-keys.md
  - Lists: lists.md
  - Tables: tables.md
  - Messages: messages.md
  - Highlighter: highlighter.md
  - Tabs: tabs.md
  - Diagrams: diagrams.md
  - Footnotes: footnotes.md
  - Abbreviations: abbreviations.md
  - Attributes: attributes.md
  - Icons & Emojis: icons-emojis.md
  - Cards: cards.md
  - Snippets: snippets.md
